CONFIG_ZMK_KEYBOARD_NAME="sweep keeb"

CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# this setting turns on LED functionality
# LEDs or displays can be turned on or off with this setting
CONFIG_ZMK_EXT_POWER=y

# this turns on display functionality
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# turns on underglow and glow keys
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=2 #spectrum effect on start

CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Don't turn off RGB underglow when keyboard goes into idle state
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n

CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=5
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=5
CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=1
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y

# this is mouse keys functionality
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=8
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
